const context = this.getContextByIndex(this.getSelectedIndex());

if (context) {
    const data = context.getObject();
    modeloPageDetail.oData.config.table = data.TABLE_NAME;
    modeloPageDetail.oData.config.creatable = false;
    modeloPageDetail.oData.config.updatable = false;
    modeloPageDetail.oData.config.deletable = false;
    modeloPageDetail.refresh();
    controller.updateFields();
    diaTables.close();
}
